const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='awakened_state_v1';
const defaults={name:'PLAYER',xp:0,level:1,streak:0,focus:0,quests:[{id:1,title:'Complete your first mission',cat:'PERSONAL',diff:'EASY',xp:25,done:false},{id:2,title:'25 minute focused study',cat:'STUDY',diff:'NORMAL',xp:35,done:false}],stats:{Strength:10,Intelligence:10,Discipline:10,Focus:10,Endurance:10,Consistency:10,Knowledge:10,Energy:10},habits:[],journal:[],bosses:[{id:1,title:'MASTER YOUR NEXT GOAL',hp:1000,max:1000}],achievements:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||defaults;let page='home';let deferredInstall=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function levelNeed(l){return 100+Math.floor(l**1.35)*50} function rank(){return ['E','D','C','B','A','S','SS','SSS'][Math.min(7,Math.floor((state.level-1)/5))]}
function addXP(n){state.xp+=n;let old=state.level;while(state.xp>=levelNeed(state.level)){state.xp-=levelNeed(state.level);state.level++}save();if(state.level>old){toast('LEVEL UP',`Level ${old} → ${state.level}`)}else{const f=document.createElement('div');f.className='xpfloat';f.textContent=`+${n} XP`;document.body.append(f);setTimeout(()=>f.remove(),1200)}}
function toast(title,msg){const t=document.createElement('div');t.className='toast';t.innerHTML=`<b>[ ${title} ]</b><div class="muted">${msg}</div>`;document.body.append(t);setTimeout(()=>t.remove(),2600)}
function layout(title,body){$('#pageTitle').textContent=title;$('#content').innerHTML=body}
function home(){const need=levelNeed(state.level),pct=Math.min(100,state.xp/need*100),done=state.quests.filter(q=>q.done).length;layout('COMMAND CENTER',`<div class="grid"><div class="card wide"><span class="eyebrow">PLAYER</span><h2>${esc(state.name)}</h2><div class="muted">RANK ${rank()} · LEVEL ${state.level}</div><div class="bar"><i style="width:${pct}%"></i></div><div class="row"><b>${state.xp} XP</b><span class="muted">/ ${need} XP</span><span class="pill">STREAK ${state.streak}</span></div></div><div class="card"><span class="eyebrow">TODAY</span><div class="stat">${done}/${state.quests.length}</div><div class="muted">quests completed</div><button class="primary" onclick="go('quests')">VIEW QUESTS</button></div><div class="card"><span class="eyebrow">FOCUS</span><div class="stat">${state.focus}m</div><div class="muted">total today</div><button class="primary" onclick="go('focus')">START FOCUS</button></div><div class="card wide"><span class="eyebrow">MISSIONS</span>${state.quests.slice(0,5).map(q=>questHTML(q)).join('')}${!state.quests.length?'<p class="muted">No active missions detected.</p>':''}</div><div class="card"><span class="eyebrow">SYSTEM MESSAGE</span><h3>Today's actions determine tomorrow's level.</h3><p class="muted">Keep the chain moving. Small completed actions compound.</p></div></div>`)}
function questHTML(q){return `<div class="quest"><button class="check ${q.done?'done':''}" onclick="toggleQuest(${q.id})">${q.done?'✓':'○'}</button><div style="flex:1"><b>${esc(q.title)}</b><div class="muted">${q.cat} · ${q.diff}</div></div><span class="xp">+${q.xp}</span></div>`}
function quests(){layout('QUEST DATABASE',`<div class="row" style="justify-content:space-between;margin-bottom:14px"><span class="muted">${state.quests.length} registered missions</span><button class="primary" onclick="questModal()">+ CREATE QUEST</button></div><div class="card full">${state.quests.map(questHTML).join('')||'<p class="muted">No active missions detected.</p>'}</div>`)}
function questModal(){modal(`<h2>REGISTER QUEST</h2><input id="qtitle" class="field" placeholder="Quest name"><select id="qcat" class="field"><option>STUDY</option><option>FITNESS</option><option>PERSONAL</option><option>SKILLS</option><option>DIGITAL</option><option>DISCIPLINE</option><option>CUSTOM</option></select><select id="qdiff" class="field"><option value="5">EASY · 5 XP</option><option value="15">NORMAL · 15 XP</option><option value="30">HARD · 30 XP</option><option value="60">EPIC · 60 XP</option><option value="100">LEGENDARY · 100 XP</option></select><textarea id="qdesc" class="field" placeholder="Description"></textarea><div class="row"><button class="primary" onclick="createQuest()">CREATE QUEST</button><button onclick="closeModal()">CANCEL</button></div>`)}
function createQuest(){const title=$('#qtitle').value.trim();if(!title)return toast('SYSTEM ERROR','Quest name is required.');const diff=$('#qdiff');state.quests.push({id:Date.now(),title,cat:$('#qcat').value,diff:diff.options[diff.selectedIndex].text.split(' ·')[0],xp:+diff.value,done:false,desc:$('#qdesc').value});save();closeModal();quests();toast('SYSTEM','QUEST REGISTERED')}
function toggleQuest(id){const q=state.quests.find(x=>x.id===id);if(!q||q.done)return;q.done=true;state.streak++;const stat=q.cat==='STUDY'?'Intelligence':q.cat==='FITNESS'?'Strength':'Discipline';state.stats[stat]+=5;addXP(q.xp);save();toast('QUEST COMPLETE',`+${q.xp} XP · +5 ${stat}`);render()}
function schedule(){layout('SCHEDULE',`<div class="grid"><div class="card wide"><span class="eyebrow">TODAY</span><h2>YOUR TIMELINE</h2><div class="quest"><b>06:30</b><span>Morning routine</span></div><div class="quest"><b>07:00</b><span>Priority focus block</span></div><div class="quest"><b>09:00</b><span>School / College / Work</span></div><div class="quest"><b>18:30</b><span>Quest window</span></div><div class="quest"><b>21:00</b><span>Revision + review</span></div></div><div class="card"><span class="eyebrow">SYSTEM ADAPTATION</span><h3>Build around reality.</h3><p class="muted">This starter scheduler avoids claiming automatic calendar sync. Add your real events in the full backend version.</p></div></div>`)}
let timer=null,remaining=1500;function focus(){layout('FOCUS MODE',`<div class="card full" style="text-align:center"><span class="eyebrow">FOCUS QUEST</span><div id="timer" class="stat" style="font-size:64px;margin:25px">${fmt(remaining)}</div><div class="row" style="justify-content:center"><button class="primary" onclick="startTimer()">START</button><button onclick="resetTimer()">RESET</button></div><p class="muted">25 / 5 mode · completion awards 25 XP</p></div>`)}function startTimer(){if(timer)return;timer=setInterval(()=>{remaining--;if($('#timer'))$('#timer').textContent=fmt(remaining);if(remaining<=0){clearInterval(timer);timer=null;state.focus+=25;addXP(25);remaining=1500;save();toast('FOCUS QUEST COMPLETE','+25 XP')}} ,1000)}function resetTimer(){clearInterval(timer);timer=null;remaining=1500;focus()}function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function habits(){layout('HABITS',`<div class="grid"><div class="card wide"><span class="eyebrow">CONSISTENCY</span><h2>BUILD THE CHAIN</h2><div class="row"><input id="habit" class="field" placeholder="New habit"><button class="primary" onclick="addHabit()">ADD</button></div>${state.habits.map((h,i)=>`<div class="quest"><span>◇ ${esc(h)}</span><button class="pill" onclick="completeHabit(${i})">+5 XP</button></div>`).join('')}</div><div class="card"><span class="eyebrow">STREAK</span><div class="stat">${state.streak}</div><div class="muted">completed actions</div></div></div>`)}function addHabit(){let h=$('#habit').value.trim();if(h){state.habits.push(h);save();habits()}}function completeHabit(i){state.streak++;state.stats.Consistency+=3;addXP(5);save();toast('HABIT COMPLETE','+5 XP · +3 Consistency');habits()}
function bosses(){layout('BOSS ARENA',`<div class="grid">${state.bosses.map(b=>`<div class="card wide"><span class="eyebrow">ACTIVE BOSS</span><h2>${esc(b.title)}</h2><div class="row"><b>HP ${b.hp}</b><span class="muted">/ ${b.max}</span></div><div class="bar"><i style="width:${b.hp/b.max*100}%"></i></div><button class="primary" onclick="damageBoss(${b.id})">COMPLETE BOSS ACTION · -100 HP</button></div>`).join('')}</div>`)}function damageBoss(id){const b=state.bosses.find(x=>x.id===id);b.hp=Math.max(0,b.hp-100);addXP(15);if(!b.hp){state.achievements.push('BOSS SLAYER');toast('BOSS DEFEATED','MASTER YOUR NEXT GOAL')}save();bosses()}
function skills(){layout('SKILL MATRIX',`<div class="grid">${Object.entries(state.stats).map(([k,v])=>`<div class="card"><span class="eyebrow">SKILL NODE</span><h2>${k}</h2><div class="bar"><i style="width:${Math.min(100,v)}%"></i></div><b>LV ${Math.floor(v/10)}</b><div class="muted">${v}/100 progression</div></div>`).join('')}</div>`)}
function analytics(){const done=state.quests.filter(q=>q.done).length;layout('ANALYTICS',`<div class="grid"><div class="card"><span class="eyebrow">QUESTS</span><div class="stat">${done}</div><div class="muted">completed</div></div><div class="card"><span class="eyebrow">XP</span><div class="stat">${state.xp}</div><div class="muted">current level XP</div></div><div class="card"><span class="eyebrow">FOCUS</span><div class="stat">${state.focus}m</div><div class="muted">tracked today</div></div><div class="card full"><h2>PERFORMANCE</h2><p class="muted">This local-first build tracks your core progression. Cloud analytics can be connected later without changing the UI model.</p></div></div>`)}
function journal(){layout('JOURNAL',`<div class="card full"><span class="eyebrow">PRIVATE LOG</span><textarea id="entry" class="field" rows="6" placeholder="What did you complete? What did you learn?"></textarea><button class="primary" onclick="saveJournal()">SAVE ENTRY</button>${state.journal.map(e=>`<div class="quest"><div><b>${e.date}</b><div class="muted">${esc(e.text)}</div></div></div>`).join('')}</div>`)}function saveJournal(){const t=$('#entry').value.trim();if(t){state.journal.unshift({date:new Date().toLocaleDateString(),text:t});save();journal();toast('SYSTEM','JOURNAL ENTRY SAVED')}}
function profile(){layout('PLAYER PROFILE',`<div class="grid"><div class="card wide"><span class="eyebrow">PLAYER ID</span><h2>${esc(state.name)}</h2><p class="muted">RANK ${rank()} · LEVEL ${state.level}</p><div class="row"><span class="pill">STREAK ${state.streak}</span><span class="pill">ACHIEVEMENTS ${state.achievements.length}</span></div></div><div class="card"><span class="eyebrow">TITLE</span><h2>${state.level>=10?'DISCIPLINED':'AWAKENED'}</h2><div class="muted">Equipped title</div></div><div class="card full"><h2>INITIALIZE PLAYER</h2><div class="row"><input id="playerName" class="field" value="${esc(state.name)}"><button class="primary" onclick="setName()">UPDATE</button></div></div></div>`)}function setName(){let n=$('#playerName').value.trim();if(n){state.name=n.toUpperCase();save();profile();toast('SYSTEM','PLAYER PROFILE UPDATED')}}
function core(){modal(`<span class="eyebrow">SYSTEM CORE</span><h2>DAILY ADAPTATION</h2><p class="muted">I can help prioritize your registered quests using the data currently stored in this device. This demo does not send your private data to an AI service.</p><button class="primary" onclick="corePlan()">GENERATE PLAN</button><button onclick="closeModal()">CLOSE</button>`)}function corePlan(){const open=state.quests.filter(q=>!q.done).slice(0,3).map((q,i)=>`${i+1}. ${q.title}`).join('<br>')||'No open quests. Create your next mission.';modal(`<span class="eyebrow">SYSTEM CORE</span><h2>TODAY'S PRIORITY</h2><p>${open}</p><p class="muted">Suggested rule: complete one high-value quest, then use a focus session.</p><button class="primary" onclick="closeModal()">ACKNOWLEDGE</button>`)}
function modal(html){$('#modal').innerHTML=`<div class="dialog">${html}</div>`;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function go(p){page=p;render()}function render(){ $$('.sidebar nav button,.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));({home,quests,schedule,focus,habits,bosses,skills,analytics,journal,profile}[page]||home)()}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));$('#coreBtn').onclick=core;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
window.toggleQuest=toggleQuest;window.questModal=questModal;window.createQuest=createQuest;window.go=go;window.startTimer=startTimer;window.resetTimer=resetTimer;window.addHabit=addHabit;window.completeHabit=completeHabit;window.damageBoss=damageBoss;window.saveJournal=saveJournal;window.setName=setName;window.corePlan=corePlan;window.closeModal=closeModal;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden');$('#installBtn').onclick=()=>{deferredInstall.prompt();deferredInstall=null;$('#installBtn').classList.add('hidden')}});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
let logs=['[SYSTEM BOOTING...]','[INITIALIZING PLAYER DATABASE...]','[LOADING PROGRESSION ENGINE...]','[CALIBRATING HUD...]','[SYSTEM ONLINE]'];let i=0;const iv=setInterval(()=>{$('#bootlog').textContent+=logs[i]+'\n';i++;if(i===logs.length){clearInterval(iv);setTimeout(()=>{$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');render()},500)}},500);
